Repository PulseTile/PulseTile-React-Core, pull requests merged in 2018-10, with the labels that each got.

#242 Issue #25 When sidebar menu is expanded, button should read X Close
  src/components/containers/Header/HeaderToolbar/HeaderToolbar.js
Labels: 3 - Review, PulseTile

#243 Home buttons
  src/components/containers/TopHeader/TopHeader.js
  src/components/containers/TopHeader/__tests__/TopHeader.test.js
  src/components/containers/TopHeader/__tests__/__snapshots__/TopHeader.test.js.snap
  src/components/containers/UserPanel/UserPanel.js
  src/components/containers/UserPanel/__tests__/__snapshots__/UserPanel.test.js.snap
  src/themes.config.js
Labels: 3 - Review, PulseTile

#249 resolved the issue regarding can't get property 'type' of the link which is value is undefined or NULL
  src/index.html
Labels: 3 - Review

#250 RecordsOfTable updating
  src/components/form-fields/RecordsOfTable/RecordsOfTable.js
  src/components/form-fields/RecordsOfTable/RecordsOfTablePopover.js
  src/components/form-fields/RecordsOfTable/RecordsOfTablePopoverDiagnosis.js
  src/components/form-fields/RecordsOfTable/RecordsOfTablePopoverMedications.js
  src/components/form-fields/RecordsOfTable/RecordsOfTableView.js
  src/components/form-fields/RecordsOfTable/__tests__/RecordsOfTable.test.js
  src/components/form-fields/RecordsOfTable/__tests__/RecordsOfTablePopover.test.js
  src/components/form-fields/RecordsOfTable/__tests__/RecordsOfTablePopoverDiagnosis.test.js
  src/components/form-fields/RecordsOfTable/__tests__/RecordsOfTablePopoverMedications.test.js
  src/components/form-fields/RecordsOfTable/__tests__/RecordsOfTableView.test.js
  src/components/form-fields/RecordsOfTable/__tests__/__snapshots__/RecordsOfTable.test.js.snap
  src/components/form-fields/RecordsOfTable/__tests__/__snapshots__/RecordsOfTablePopover.test.js.snap
  src/components/form-fields/RecordsOfTable/__tests__/__snapshots__/RecordsOfTablePopoverDiagnosis.test.js.snap
  src/components/form-fields/RecordsOfTable/__tests__/__snapshots__/RecordsOfTablePopoverMedications.test.js.snap
  src/components/form-fields/RecordsOfTable/__tests__/__snapshots__/RecordsOfTableView.test.js.snap
  src/components/form-fields/RecordsOfTable/forms.config.js
  src/components/form-fields/RecordsOfTable/functions.js
  src/components/theme/config/recordsOfTable/recordsOfTable.js
  src/components/theme/config/recordsOfTable/recordsOfTableDetails.js
  src/components/theme/config/recordsOfTable/recordsOfTableFunctions.js
  src/components/theme/config/recordsOfTable/recordsOfTablePopover.js
  src/config/for-test.constants.js
Labels: 3 - Review, review

#253 HeaderToolbar snapshot
  src/components/containers/Header/__tests__/__snapshots__/HeaderToolbar.test.js.snap
Labels: 3 - Review, review

#255 Update dependency
  package-lock.json
  package.json
Labels: 3 - Review

#256 User birthdate fixing
  src/components/containers/TopHeader/__tests__/__snapshots__/TopHeader.test.js.snap
  src/components/containers/UserPanel/UserAccountPanel.js
  src/components/containers/UserPanel/__tests__/__snapshots__/UserAccountPanel.test.js.snap
  src/components/containers/UserPanel/__tests__/__snapshots__/UserPanel.test.js.snap
Labels: 3 - Review, review

#257 Muted window title change from set-title.duck.js
  src/ducks/set-title.duck.js
Labels: 3 - Review

#259 Fixed mobile menu
  src/ducks/set-sidebar-visibility.js
Labels: 3 - Review

#261 Unit tests updating
  src/components/pages/PatientsSummary/__tests__/PatientsSummaryPanel.test.js
  src/components/pages/PatientsSummary/functions.js
Labels: 3 - Review, review

#262 Unit test - fix
  src/components/pages/PatientsSummary/__tests__/PatientsSummaryPanel.test.js
Labels: 3 - Review, review

#269 Showcase. Mobile experience.
  src/components/containers/Header/HeaderToolbar/HeaderToolbar.js
  src/components/containers/Header/__tests__/HeaderToolbar.test.js
  src/components/containers/Header/__tests__/__snapshots__/HeaderToolbar.test.js.snap
  src/components/containers/NavSearch/NavSearch.js
  src/components/containers/NavSearch/__tests__/__snapshots__/NavSearch.test.js.snap
  src/components/containers/TopHeader/__tests__/__snapshots__/TopHeader.test.js.snap
  src/components/containers/UserPanel/UserPanel.js
  src/components/containers/UserPanel/__tests__/__snapshots__/UserPanel.test.js.snap
Labels: 3 - Review, review

#270 added Dockerfile
  Dockerfile
Labels: 3 - Review

#272 Fixed problem with Patient Summary tables before loading
  src/components/containers/SortableTable/SortableTable.js
  src/components/pages/PatientsSummary/SimpleDashboardPanel.js
Labels: 3 - Review, review

#273 Fixed bug with selecting empty item from Patient Summary screen
  src/components/pages/Allergies/Allergies.js
  src/components/pages/Contacts/Contacts.js
  src/components/pages/Diagnosis/Diagnosis.js
  src/components/pages/Medications/Medications.js
  src/components/pages/Medications/__tests__/__snapshots__/Medications.test.js.snap
Labels: 3 - Review, review

#274 Develop local -> Develop parent
  Dockerfile
  README.md
Labels: 3 - Review, review

#281 Changes for api/initialise
  package-lock.json
  src/ducks/fetch-initialise.duck.js
  src/ducks/initialise-app.duck.js
  src/utils/redirect-helpers.utils.js
Labels: 3 - Review, review
